spring.application.name=workout-and-nutrition-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5434/workout_nutrition
spring.datasource.username=workout
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway config
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

#URLS
user.service.url=http://host.docker.internal:8081

jwt.secret=${JWT_SECRET}

feign.client.config.ai-client.connectTimeout: 5000
feign.client.config.ai-client.readTimeout: 60000
